version: '3.9'
services:
  app:
    network_mode: host
    container_name: smart_plug
    build: .
    ports:
      - 8081:8081
    restart: on-failure      
    volumes:
      - .:/app
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgres_container
    build: ./postgres/
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
