package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"github.com/IvanBorislavovDimitrov/smart-charger/graph/model"
)

// CreatePlug is the resolver for the createPlug field.
func (r *mutationResolver) CreatePlug(ctx context.Context, input model.NewPlug) (*model.Plug, error) {
	return r.plugService.AddPlug(input)
}

// ListPlugs is the resolver for the listPlugs field.
func (r *queryResolver) ListPlugs(ctx context.Context) ([]*model.Plug, error) {
	panic(fmt.Errorf("not implemented: ListPlugs - listPlugs"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
